destination: _site/kdp
exclude:
  - "*.yml"
# This is the only way I could find to have print images display correctly
imageWidth: 1600px
imageHeight: 900px
coverImage:
responsibilityModelImage: |
  width: 2121px;
  height: 774px;
devExImage: |
  width: 1161px;
  height: 1191px;
responsibilityTriadImage: |
  width: 1161px;
  height: 1191px;
radarChartImage: |
  width: 666px;
  height: 524px;
devopsImage: |
  width: 1000px;
  height: 503px;