destination: _site/kdp
exclude:
  - "*.yml"
# This is the only way I could find to have print images display correctly
imageWidth: 1600px
imageHeight: 900px
coverImage:
# Images needed explicit dimensions otherwise they would be scaled oddly.
responsibilityModelImage: |
  width: 2121px;
  height: 774px;
devExImage: |
  width: 1161px;
  height: 1191px;
responsibilityTriadImage: |
  width: 1161px;
  height: 1191px;
radarChartImage: |
  width: 666px;
  height: 524px;
devopsImage: |
  width: 1000px;
  height: 503px;
deeasImage: |
  width: 1200px;
  height: 1920px;
# The TOC for Kindle needs to be a list of paragraphs:
# https://ebooks.stackexchange.com/a/7989
tocParent: div
tocChild: p
# Printed books can do some strange things with table wrapping. Table headers in
# particular seem to be susceptible to words being broken over two lines for no
# good reason, and none of the CSS or table tricks like width attributes or <col>
# elements fixed it. This invisible spacing image was how I could force cells to
# not break.
cellSpacer: ' <img alt="Invisible spacing" src="images/pixel.png" style="width: 100px; height: 1px"/>'
